[project]

name = 'info.gianlucacosta.wikiprism'

version = '0.0.0'

description = 'Parse wiki pages and create dictionaries, fast, with Python'

authors = [{ name = "Gianluca Costa", email = "gianluca@gianlucacosta.info" }]

dependencies = ['info.gianlucacosta.eos.core~=2.0']

requires-python = ">=3.14, <4.0"

readme = 'README.md'

license = { text = "MIT" }

keywords = [
  'library',
  'extract',
  'wiki',
  'pages',
  'dictionary',
  'terms',
  'pipeline',
]

classifiers = [
  'Development Status :: 5 - Production/Stable',
  'Intended Audience :: Developers',
  'License :: OSI Approved :: MIT License',
  'Operating System :: OS Independent',
  'Programming Language :: Python',
  'Topic :: Text Processing :: Linguistic',
]


[project.urls]

homepage = "https://github.com/giancosta86/wikiprism"

repository = 'https://github.com/giancosta86/wikiprism'


[build-system]

requires = ["pdm-backend"]
build-backend = "pdm.backend"


[dependency-groups]

dev = [
  "ruff ~= 0.16.4",
  "pytest ~= 9.1.1",
  "pytest-cov ~= 7.1.0",
  "mypy ~= 2.3.1",
]


[tool.pdm]

distribution = true


[tool.pdm.build]

includes = ["src"]

source-includes = [
  'src/**/test_*.py',
  'src/**/*_test.py',
  'src/**/test_*/**',
  'src/**/*_test/**',
]


[tool.pdm.scripts]

clean = 'rm -rf .mypy_cache .pdm-build .pytest_cache .ruff_cache .venv dist htmlcov .coverage .pdm-python pdm.lock'

lint = 'ruff check src'

check-types = 'mypy src'

test = 'pytest'

verify = { composite = ['lint', 'check-types', 'test'] }
